GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "name",
    "dateOfBirth": "2026-01-01",
    "ssn": "999999-999X",
    "gender": "male",
    "occupation": "my occupation"
}